routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::prefix('admin')
    ->namespace('Admin')
    ->name('admin.')
    ->group(function () {
        Route::resource('lang', 'LangController')->except('show');
        Route::resource('projects', 'ProjectController')->except('show');
        Route::resource('projects.images', 'ProjectImageController')->except('show');
        Route::resource('projects.lang', 'ProjectLangController')->except('show');

        Route::resource('products', 'ProductController')->except('show');
        Route::resource('products.images', 'ProductImageController')->except('show');
        Route::resource('products.lang', 'ProductLangController')->except('show');

        Route::get('about', 'AboutController@edit')->name('about.edit');
        Route::put('about', 'AboutController@update')->name('about.update');

        Route::get('frontend/{lang}', 'FrontendController@edit')->name('frontend.edit');
        Route::put('frontend/{lang}', 'FrontendController@update')->name('frontend.update');

        Route::get('/', 'DashboardController@index');

        Route::get('first-page', 'FirstPageController@index')->name('first-page.index');
        Route::post('first-page', 'FirstPageController@saveImage')->name('first-page.images.store');

        Route::get('first-page-info', 'FirstPageInfoController@edit')->name('first-page-info.show');
        Route::post('first-page-info', 'FirstPageInfoController@update')->name('first-page-info.update');

        Route::get('material-estimator', 'MaterialEstimatorController@index')->name('material-estimator.index');
        Route::put('material-estimator', 'MaterialEstimatorController@update')->name('material-estimator.update');

        Route::get('color-center', 'ColorCenterController@index')->name('color-center.index');
        Route::post('color-center', 'ColorCenterController@store')->name('color-center.store');

        Route::get('instalation-instructions', 'InstalationInstructionController@index')->name('instalation-instructions.index');
        Route::post('instalation-instructions', 'InstalationInstructionController@store')->name('instalation-instructions.store');

        Route::get('terms', 'TermsController@edit')->name('terms.edit');
        Route::put('terms', 'TermsController@update')->name('terms.update');

        Route::get('confident', 'ConfidentController@edit')->name('confident.edit');
        Route::put('confident', 'ConfidentController@update')->name('confident.update');

        Route::resource('blog', 'BlogController');

        Route::resource('testimonials', 'TestimonialController');
        Route::resource('blogs', 'BlogController');
    });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/consent', 'HomeController@setConsent');
Route::get('/about-us', 'HomeController@about');
Route::get('/projects', 'ProjectController@index');
Route::get('/projects/{project}', 'ProjectController@show');
Route::get('/products', 'ProductController@index');
Route::get('/products/{product}', 'ProductController@show');
Route::put('/lang', 'HomeController@lang');

Route::get('contact', 'HomeController@showContact');
Route::post('contact', 'HomeController@sendContact');

Route::get('material-estimator', 'HomeController@showMaterialEstimator');
Route::get('instalation-instructions', 'HomeController@showInstalationInstructions');
Route::get('color-center', 'HomeController@showColorCenter');

Route::get('terms', 'HomeController@showTerms');
Route::get('confident', 'HomeController@showConfident');

Route::get('/blog', 'HomeController@showBlogs');
Route::get('/blog/{slug}', 'HomeController@showBlog');

app/Lang.php
<?php

namespace App;

class Lang extends Model
{
    protected $fillable = ['name', 'active'];
    protected $casts = ['active' => 'boolean'];

    public function getShortNameAttribute()
    {
        return substr(strtolower($this->name), 0, 2);
    }

    public static function boot()
    {
        parent::boot();

        static::created(function ($model) {
            // create folder if it does not exist
            if (!\File::exists(resource_path("lang/$model->short_name"))) {
                \File::makeDirectory(resource_path("lang/$model->short_name"));
            }

            // copy translation file
            \File::copy(
                resource_path('lang/' . config('app.locale') . '/' . config('lang.filename') . '.php'),
                resource_path('lang/' . $model->short_name . '/' . config('lang.filename') . '.php')
            );
        });
    }

    public function scopeActives($query)
    {
        $query->where('active', true);
    }
}

app/Http/Controllers/Admin/LangController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Lang;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $langs = Lang::paginate(10);

        return view('admin.lang.index', compact('langs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.lang.create');
    }

    protected function validateFields($request)
    {
        return $this->validate($request, [
            'name' => 'required',
            'active' => 'boolean'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Lang::create($this->validateFields($request));

        return redirect()->route('admin.lang.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Lang  $lang
     * @return \Illuminate\Http\Response
     */
    public function show(Lang $lang)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Lang  $lang
     * @return \Illuminate\Http\Response
     */
    public function edit(Lang $lang)
    {
        return view('admin.lang.edit', compact('lang'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Lang  $lang
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Lang $lang)
    {
        $lang->update($this->validateFields($request));

        return redirect()->route('admin.lang.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lang  $lang
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lang $lang)
    {
        //
    }
}

resources/views/admin/lang/create.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            <a href="{{ route('admin.lang.index') }}" class="btn btn-default">
                <i class="fa fa-backward"></i>
                Inapoi
            </a>
        @endslot

        {!! Form::open()->route('admin.lang.store') !!}
            {!! Form::text('name', 'Nume') !!}
            {!! Form::select('active', 'Activ', ['Nu', 'Da'], 1) !!}
            {!! Form::submit('Salveaza')->success() !!}
        {!! Form::close() !!}
    @endbox
@endsection

resources/views/admin/lang/edit.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            Editeaza limba #{{ $lang->id }}
        @endslot

        {!! Form::open()->put()->route('admin.lang.update', [$lang->id])->fill($lang) !!}
            {!! Form::text('name', 'Nume') !!}
            {!! Form::select('active', 'Activ', ['Nu', 'Da']) !!}
            {!! Form::submit('Modifica') !!}
            {!! Form::anchor('Inapoi')->route('admin.lang.index') !!}

        {!! Form::close() !!}
    @endbox
@endsection

resources/views/admin/lang/index.blade.php
@extends('adminlte::page')

@section('content')
    @box
        @slot('buttons')
            <div class="col-md-6">
                @add(['route' => 'admin.lang.create', 'name' => 'limba'])
                @endadd
            </div>

            <div class="col-md-6">
                @search(['route' => 'admin.lang.index'])
                @endsearch
            </div>
        @endslot

        @if ($langs->count())
            <table class="table table-bordered table-hover">
                @theader(['columns' => [
                    'id' => 'Id',
                    'name' => 'Nume',
                    'active' => 'Activ',
                    'created_at' => 'Creat la',
                    'updated_at' => 'Modificat la',
                    'none' => 'Actiuni'
                ]])
                @endtheader

                <tbody>
                    @foreach ($langs as $lang)
                        <tr>
                            <td>{{ $lang->id }}</td>
                            <td>{{ $lang->name }}</td>
                            <td>{{ $lang->active ? 'Da' : 'Nu' }}</td>
                            <td>{{ $lang->created_at->format('d.m.Y H:i:s') }}</td>
                            <td>{{ $lang->updated_at->format('d.m.Y H:i:s') }}</td>
                            <td>
                                <a href="{{ route('admin.lang.edit', $lang->id) }}" class="btn btn-xs">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a href="{{ route('admin.frontend.edit', $lang->id) }}" class="btn btn-xs">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            {{ $langs->links() }}
        @else
            Nu exista inregistrari
        @endif
    @endbox
@endsection